# Generated by Django 5.1.7 on 2025-03-25 20:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='body_condition',
            field=models.CharField(blank=True, default='Хорошее', max_length=100, verbose_name='Состояние корпуса'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Чёрный'), ('white', 'Белый'), ('gold', 'Золотой'), ('silver', 'Серебристый'), ('blue', 'Синий'), ('red', 'Красный'), ('green', 'Зелёный'), ('other', 'Другой')], default='black', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Доп. изображение 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Доп. изображение 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Доп. изображение 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='includes',
            field=models.TextField(blank=True, default='Телефон, зарядное устройство', verbose_name='Комплектация'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='products/default.jpg', upload_to='products/', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='phone_model',
            field=models.CharField(default='Не указана', max_length=100, verbose_name='Модель телефона'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_condition',
            field=models.CharField(blank=True, default='Хорошее', max_length=100, verbose_name='Состояние экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.DecimalField(decimal_places=1, default=6.1, max_digits=3, verbose_name='Диагональ экрана (дюймы)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_address',
            field=models.TextField(blank=True, default='Не указан', verbose_name='Адрес продавца'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон продавца'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='battery_health',
            field=models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Здоровье аккумулятора (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('A', 'Как новый'), ('B', 'Хорошее'), ('C', 'Удовлетворительное')], max_length=1, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(default='Не указана', max_length=20, verbose_name='Память'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
